name: Test and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: zulu
          java-version: 17
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Run tests
        run: bin/kaocha

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Push to Deploy
        run: git push -f ssh://compass@compass.heartofclojure.eu:/home/compass/repo main:main
